 version: "3.8"
 services: 
    node-hello:
        build:
            context: .
        volumes: 
            - .:/node-hello
        ports:
            - 3000:3000
        image: s3817403/node-hello
        container_name: node-hello_container
        command: npm start