version: 2.1
services:
    - docker
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: s3817403/node-hello
    docker:
      - image: circleci/node:16
jobs:
  build:
    executor: docker-publisher 
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: NPM install
          command: npm install 
      - run: 
          name: audit fix
          command: npm audit fix
      - run:
          name: build
          command: docker build -t $IMAGE_NAME .
  publish-latest:
    executor: docker-publisher
    steps:
      - setup_remote_docker
      - run:
          name: Push image to docker hub
          command: docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: workflow
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: workflow