# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME : s3817403/node-hello
    docker: 
      - image: node-hello/container
        auth:
          username: s3817403
          password: $DOCKERHUB_PASSWORD
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: docker build -t $IMAGE_NAME:latest .
      - run:
          name: redirecting port
          command: docker run -p 3000:3000 $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest

workflows:
  version: 2
  build-master:
    jobs:
      - build
      #    filters:
       
       #    branches:
        #       only: master
      - publish-latest:
          requires:
            - build


