version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: s3817403/node-hello
    docker:
      - image: s3817403/takehome-assignment02:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: NPM install
          command: npm install -g install-docker-cli\
      - run: 
          name: audit fix
          command: npm audit fix
      - run:
          name: copy 
          command: COPY package*.json ./
      - run:
          name: compose
          command: docker-compose build