version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: s3817403/node-hello
    docker:
      - image: s3817403/takehome-assignment02:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: NPM install
          command: npm install -g install-docker-cli
      - run: 
          name: copy
          command: COPY . .
      - run:
          name: Build Docker image
          command: docker build -t s3817403/node-hello:latest .
