version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: z/building-on-ci
    docker:
      - image: s3817403/takehome-assignment02:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: NPM install
          command: npm install
      - run: 
          name: NPM start
          command: npm start
      - run:
          name: Build Docker image
          command: docker build -t z/building-on-ci .
