# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME : zain/node-hello
    docker:
      - image : s3817403/takehome_assignment02
jobs:
  build:
    executor : docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build image 
          command : |
            docker build -t $IMAGE_NAME:latest .
      - run:
          name: compose build
          command: docker-compose build
      - run:
          name: compose up
          command: docker-compose up
      - run:
          name: Archive Docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /temp/workspace
      - setup_remote_docker
      - run:
            name: Load archived Docker image
            command: docker load -i /tmp/workspace/image.tar
      - run:
          name: log in
          command: echo | "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name : public image to docker hub
          command: docker push $IMAGE_NAME:latest


workflows:
  version: 2
  build-master:
    jobs:
      - build
      #    filters:
       
       #    branches:
        #       only: master
      - publish-latest:
          requires:
            - build


