version: 2.1
services:
    - docker
jobs:
  build:
    working_directory: -/node-hello
    environment:
      IMAGE_NAME: s3817403/node-hello
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: NPM install
          command: npm install -g install-docker-cli
      - run: 
          name: audit fix
          command: npm audit fix
      - run:
          name: copy 
          command: COPY package*.json ./
      - run:
          name: build
          command: docker build -t $IMAGE_NAME .